
language: node_js
node_js:
  - "8"
cache:
  directories:
  - node_modules
before_install:
  - npm install -g @2fd/graphdoc
script:
  - npm test
install:
  - npm install
after_success:
  - chmod +x src/travis/publish.sh
  - chmod +x src/travis/deploy-gh-pages.sh
  - docker build -t ${TRAVIS_REPO_SLUG} -f DockerFile .
  - src/travis/publish.sh
  - src/travis/deploy-gh-pages.sh
